export interface Character {
    name: string;
    num: string;
    img_link: string;
}

export const CHAR_LIST: Character[] = [
    {name: 'MARIO', num: '01', img_link: '/assets_v2/img/fighter/thumb_h/mario.png'},
    {name: 'DONKEY KONG', num: '02', img_link: '/assets_v2/img/fighter/thumb_h/donkey_kong.png'},
    {name: 'LINK', num: '03', img_link: '/assets_v2/img/fighter/thumb_h/link.png'},
    {name: 'SAMUS', num: '04', img_link: '/assets_v2/img/fighter/thumb_h/samus.png'},
    {name: 'DARK SAMUS', num: '04e', img_link: '/assets_v2/img/fighter/thumb_h/dark_samus.png'},
    {name: 'YOSHI', num: '05', img_link: '/assets_v2/img/fighter/thumb_h/yoshi.png'},
    {name: 'KIRBY', num: '06', img_link: '/assets_v2/img/fighter/thumb_h/kirby.png'},
    {name: 'FOX', num: '07', img_link: '/assets_v2/img/fighter/thumb_h/fox.png'},
    {name: 'PIKACHU', num: '08', img_link: '/assets_v2/img/fighter/thumb_h/pikachu.png'},
    {name: 'LUIGI', num: '09', img_link: '/assets_v2/img/fighter/thumb_h/luigi.png'},
    {name: 'NESS', num: '10', img_link: '/assets_v2/img/fighter/thumb_h/ness.png'},
    {name: 'CAPTAIN FALCON', num: '11', img_link: '/assets_v2/img/fighter/thumb_h/captain_falcon.png'},
    {name: 'JIGGLYPUFF', num: '12', img_link: '/assets_v2/img/fighter/thumb_h/jigglypuff.png'},
    {name: 'PEACH', num: '13', img_link: '/assets_v2/img/fighter/thumb_h/peach.png'},
    {name: 'DAISY', num: '13e', img_link: '/assets_v2/img/fighter/thumb_h/daisy.png'},
    {name: 'BOWSER', num: '14', img_link: '/assets_v2/img/fighter/thumb_h/bowser.png'},
    {name: 'ICE CLIMBERS', num: '15', img_link: '/assets_v2/img/fighter/thumb_h/ice_climbers.png'},
    {name: 'SHEIK', num: '16', img_link: '/assets_v2/img/fighter/thumb_h/sheik.png'},
    {name: 'ZELDA', num: '17', img_link: '/assets_v2/img/fighter/thumb_h/zelda.png'},
    {name: 'DR. MARIO', num: '18', img_link: '/assets_v2/img/fighter/thumb_h/dr_mario.png'},
    {name: 'PICHU', num: '19', img_link: '/assets_v2/img/fighter/thumb_h/pichu.png'},
    {name: 'FALCO', num: '20', img_link: '/assets_v2/img/fighter/thumb_h/falco.png'},
    {name: 'MARTH', num: '21', img_link: '/assets_v2/img/fighter/thumb_h/marth.png'},
    {name: 'LUCINA', num: '21e', img_link: '/assets_v2/img/fighter/thumb_h/lucina.png'},
    {name: 'YOUNG LINK', num: '22', img_link: '/assets_v2/img/fighter/thumb_h/young_link.png'},
    {name: 'GANONDORF', num: '23', img_link: '/assets_v2/img/fighter/thumb_h/ganondorf.png'},
    {name: 'MEWTWO', num: '24', img_link: '/assets_v2/img/fighter/thumb_h/mewtwo.png'},
    {name: 'ROY', num: '25', img_link: '/assets_v2/img/fighter/thumb_h/roy.png'},
    {name: 'CHROM', num: '25e', img_link: '/assets_v2/img/fighter/thumb_h/chrom.png'},
    {name: 'MR. GAME & WATCH', num: '26', img_link: '/assets_v2/img/fighter/thumb_h/mr_game_and_watch.png'},
    {name: 'META KNIGHT', num: '27', img_link: '/assets_v2/img/fighter/thumb_h/meta_knight.png'},
    {name: 'PIT', num: '28', img_link: '/assets_v2/img/fighter/thumb_h/pit.png'},
    {name: 'DARK PIT', num: '28e', img_link: '/assets_v2/img/fighter/thumb_h/dark_pit.png'},
    {name: 'ZERO SUIT SAMUS', num: '29', img_link: '/assets_v2/img/fighter/thumb_h/zero_suit_samus.png'},
    {name: 'WARIO', num: '30', img_link: '/assets_v2/img/fighter/thumb_h/wario.png'},
    {name: 'SNAKE', num: '31', img_link: '/assets_v2/img/fighter/thumb_h/snake.png'},
    {name: 'IKE', num: '32', img_link: '/assets_v2/img/fighter/thumb_h/ike.png'},
    {name: 'POKEMON TRAINER', num: '33', img_link: '/assets_v2/img/fighter/thumb_h/pokemon_trainer.png'},
    {name: 'DIDDY KONG', num: '36', img_link: '/assets_v2/img/fighter/thumb_h/diddy_kong.png'},
    {name: 'LUCAS', num: '37', img_link: '/assets_v2/img/fighter/thumb_h/lucas.png'},
    {name: 'SONIC', num: '38', img_link: '/assets_v2/img/fighter/thumb_h/sonic.png'},
    {name: 'KING DEDEDE', num: '39', img_link: '/assets_v2/img/fighter/thumb_h/king_dedede.png'},
    {name: 'OLIMAR', num: '40', img_link: '/assets_v2/img/fighter/thumb_h/olimar.png'},
    {name: 'LUCARIO', num: '41', img_link: '/assets_v2/img/fighter/thumb_h/lucario.png'},
    {name: 'R.O.B.', num: '42', img_link: '/assets_v2/img/fighter/thumb_h/rob.png'},
    {name: 'TOON LINK', num: '43', img_link: '/assets_v2/img/fighter/thumb_h/toon_link.png'},
    {name: 'WOLF', num: '44', img_link: '/assets_v2/img/fighter/thumb_h/wolf.png'},
    {name: 'VILLAGER', num: '45', img_link: '/assets_v2/img/fighter/thumb_h/villager.png'},
    {name: 'MEGA MAN', num: '46', img_link: '/assets_v2/img/fighter/thumb_h/mega_man.png'},
    {name: 'Wii Fit TRAINER', num: '47', img_link: '/assets_v2/img/fighter/thumb_h/wii_fit_trainer.png'},
    {name: 'ROSALINA & LUMA', num: '48', img_link: '/assets_v2/img/fighter/thumb_h/rosalina_and_luma.png'},
    {name: 'LITTLE MAC', num: '49', img_link: '/assets_v2/img/fighter/thumb_h/little_mac.png'},
    {name: 'GRENINJA', num: '50', img_link: '/assets_v2/img/fighter/thumb_h/greninja.png'},
    {name: 'Mii FIGHTER', num: '51', img_link: '/assets_v2/img/fighter/thumb_h/mii_fighter.png'},
    {name: 'PALUTENA', num: '54', img_link: '/assets_v2/img/fighter/thumb_h/palutena.png'},
    {name: 'PAC-MAN', num: '55', img_link: '/assets_v2/img/fighter/thumb_h/pac_man.png'},
    {name: 'ROBIN', num: '56', img_link: '/assets_v2/img/fighter/thumb_h/robin.png'},
    {name: 'SHULK', num: '57', img_link: '/assets_v2/img/fighter/thumb_h/shulk.png'},
    {name: 'BOWSER JR.', num: '58', img_link: '/assets_v2/img/fighter/thumb_h/bowser_jr.png'},
    {name: 'DUCK HUNT', num: '59', img_link: '/assets_v2/img/fighter/thumb_h/duck_hunt.png'},
    {name: 'RYU', num: '60', img_link: '/assets_v2/img/fighter/thumb_h/ryu.png'},
    {name: 'KEN', num: '60e', img_link: '/assets_v2/img/fighter/thumb_h/ken.png'},
    {name: 'CLOUD', num: '61', img_link: '/assets_v2/img/fighter/thumb_h/cloud.png'},
    {name: 'CORRIN', num: '62', img_link: '/assets_v2/img/fighter/thumb_h/corrin.png'},
    {name: 'BAYONETTA', num: '63', img_link: '/assets_v2/img/fighter/thumb_h/bayonetta.png'},
    {name: 'INKLING', num: '64', img_link: '/assets_v2/img/fighter/thumb_h/inkling.png'},
    {name: 'RIDLEY', num: '65', img_link: '/assets_v2/img/fighter/thumb_h/ridley.png'},
    {name: 'SIMON', num: '66', img_link: '/assets_v2/img/fighter/thumb_h/simon.png'},
    {name: 'RICHTER', num: '66e', img_link: '/assets_v2/img/fighter/thumb_h/richter.png'},
    {name: 'KING K. ROOL', num: '67', img_link: '/assets_v2/img/fighter/thumb_h/king_k_rool.png'},
    {name: 'ISABELLE', num: '68', img_link: '/assets_v2/img/fighter/thumb_h/shizue.png'},
    {name: 'INCINEROAR', num: '69', img_link: '/assets_v2/img/fighter/thumb_h/gaogaen.png'},
    {name: 'PIRANHA PLANT', num: '70', img_link: '/assets_v2/img/fighter/thumb_h/packun_flower.png'},
    {name: 'JOKER', num: '71', img_link: '/assets_v2/img/fighter/thumb_h/joker.png'},
    {name: 'HERO', num: '72', img_link: '/assets_v2/img/fighter/thumb_h/dq_hero.png'},
    {name: 'BANJO & KAZOOIE', num: '73', img_link: '/assets_v2/img/fighter/thumb_h/banjo_and_kazooie.png'},
    {name: 'TERRY', num: '74', img_link: '/assets_v2/img/fighter/thumb_h/terry.png'},
    {name: 'BYLETH', num: '75', img_link: '/assets_v2/img/fighter/thumb_h/byleth.png'},
]